[package]
name = "gg"
version = "0.1.0"
authors = ["KCTF <maxim.gorishniy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
bevy = { version = "0.5.0", features = ["dynamic"] }
